# Generated by Django 6.0 on 2026-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_quiz_id', models.IntegerField(unique=True, verbose_name='ID bài học Moodle')),
                ('chapter_name', models.CharField(max_length=200, verbose_name='Tên chương')),
                ('skill_tag', models.CharField(max_length=100, verbose_name='Kỹ năng trọng tâm')),
                ('difficulty_level', models.IntegerField(default=1, verbose_name='Độ khó')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybrid_alpha', models.FloatField(default=0.5, verbose_name='Trọng số Alpha')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
